/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class DeviceRequest implements Serializable {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("deviceOs")
  private String deviceOs = null;
  @SerializedName("fcmToken")
  private String fcmToken = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDeviceOs() {
    return deviceOs;
  }
  public void setDeviceOs(String deviceOs) {
    this.deviceOs = deviceOs;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFcmToken() {
    return fcmToken;
  }
  public void setFcmToken(String fcmToken) {
    this.fcmToken = fcmToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceRequest deviceRequest = (DeviceRequest) o;
    return (this.id == null ? deviceRequest.id == null : this.id.equals(deviceRequest.id)) &&
        (this.deviceOs == null ? deviceRequest.deviceOs == null : this.deviceOs.equals(deviceRequest.deviceOs)) &&
        (this.fcmToken == null ? deviceRequest.fcmToken == null : this.fcmToken.equals(deviceRequest.fcmToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.deviceOs == null ? 0: this.deviceOs.hashCode());
    result = 31 * result + (this.fcmToken == null ? 0: this.fcmToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceRequest {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  deviceOs: ").append(deviceOs).append("\n");
    sb.append("  fcmToken: ").append(fcmToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
