/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ApiError;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class LinkLoginResponse implements Serializable {
  
  @SerializedName("href")
  private String href = null;
  @SerializedName("apiError")
  private ApiError apiError = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ApiError getApiError() {
    return apiError;
  }
  public void setApiError(ApiError apiError) {
    this.apiError = apiError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkLoginResponse linkLoginResponse = (LinkLoginResponse) o;
    return (this.href == null ? linkLoginResponse.href == null : this.href.equals(linkLoginResponse.href)) &&
        (this.apiError == null ? linkLoginResponse.apiError == null : this.apiError.equals(linkLoginResponse.apiError));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.href == null ? 0: this.href.hashCode());
    result = 31 * result + (this.apiError == null ? 0: this.apiError.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkLoginResponse {\n");
    
    sb.append("  href: ").append(href).append("\n");
    sb.append("  apiError: ").append(apiError).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
