/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ApiError;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class TokenResponse implements Serializable {
  
  @SerializedName("token")
  private String token = null;
  public enum TokenTypeEnum {
     deviceVerification,  smsClientVerification,  smsServerVerification,  refresh,  access, 
  };
  @SerializedName("tokenType")
  private TokenTypeEnum tokenType = null;
  @SerializedName("expires")
  private Date expires = null;
  @SerializedName("apiError")
  private ApiError apiError = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TokenTypeEnum getTokenType() {
    return tokenType;
  }
  public void setTokenType(TokenTypeEnum tokenType) {
    this.tokenType = tokenType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getExpires() {
    return expires;
  }
  public void setExpires(Date expires) {
    this.expires = expires;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ApiError getApiError() {
    return apiError;
  }
  public void setApiError(ApiError apiError) {
    this.apiError = apiError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenResponse tokenResponse = (TokenResponse) o;
    return (this.token == null ? tokenResponse.token == null : this.token.equals(tokenResponse.token)) &&
        (this.tokenType == null ? tokenResponse.tokenType == null : this.tokenType.equals(tokenResponse.tokenType)) &&
        (this.expires == null ? tokenResponse.expires == null : this.expires.equals(tokenResponse.expires)) &&
        (this.apiError == null ? tokenResponse.apiError == null : this.apiError.equals(tokenResponse.apiError));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.tokenType == null ? 0: this.tokenType.hashCode());
    result = 31 * result + (this.expires == null ? 0: this.expires.hashCode());
    result = 31 * result + (this.apiError == null ? 0: this.apiError.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenResponse {\n");
    
    sb.append("  token: ").append(token).append("\n");
    sb.append("  tokenType: ").append(tokenType).append("\n");
    sb.append("  expires: ").append(expires).append("\n");
    sb.append("  apiError: ").append(apiError).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
