/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeviceRequest {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("deviceOs")
  private String deviceOs = null;
  @SerializedName("deviceOsVersion")
  private String deviceOsVersion = null;
  @SerializedName("appVersion")
  private String appVersion = null;
  @SerializedName("fcmToken")
  private String fcmToken = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDeviceOs() {
    return deviceOs;
  }
  public void setDeviceOs(String deviceOs) {
    this.deviceOs = deviceOs;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDeviceOsVersion() {
    return deviceOsVersion;
  }
  public void setDeviceOsVersion(String deviceOsVersion) {
    this.deviceOsVersion = deviceOsVersion;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAppVersion() {
    return appVersion;
  }
  public void setAppVersion(String appVersion) {
    this.appVersion = appVersion;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFcmToken() {
    return fcmToken;
  }
  public void setFcmToken(String fcmToken) {
    this.fcmToken = fcmToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceRequest deviceRequest = (DeviceRequest) o;
    return (this.id == null ? deviceRequest.id == null : this.id.equals(deviceRequest.id)) &&
        (this.deviceOs == null ? deviceRequest.deviceOs == null : this.deviceOs.equals(deviceRequest.deviceOs)) &&
        (this.deviceOsVersion == null ? deviceRequest.deviceOsVersion == null : this.deviceOsVersion.equals(deviceRequest.deviceOsVersion)) &&
        (this.appVersion == null ? deviceRequest.appVersion == null : this.appVersion.equals(deviceRequest.appVersion)) &&
        (this.fcmToken == null ? deviceRequest.fcmToken == null : this.fcmToken.equals(deviceRequest.fcmToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.deviceOs == null ? 0: this.deviceOs.hashCode());
    result = 31 * result + (this.deviceOsVersion == null ? 0: this.deviceOsVersion.hashCode());
    result = 31 * result + (this.appVersion == null ? 0: this.appVersion.hashCode());
    result = 31 * result + (this.fcmToken == null ? 0: this.fcmToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceRequest {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  deviceOs: ").append(deviceOs).append("\n");
    sb.append("  deviceOsVersion: ").append(deviceOsVersion).append("\n");
    sb.append("  appVersion: ").append(appVersion).append("\n");
    sb.append("  fcmToken: ").append(fcmToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
