/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeviceDto {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("deviceOs")
  private String deviceOs = null;
  @SerializedName("deviceOsVersion")
  private String deviceOsVersion = null;
  @SerializedName("appVersion")
  private String appVersion = null;
  @SerializedName("lastLoginUtcDateTime")
  private Date lastLoginUtcDateTime = null;
  @SerializedName("lastLoginIpAddress")
  private String lastLoginIpAddress = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeviceOs() {
    return deviceOs;
  }
  public void setDeviceOs(String deviceOs) {
    this.deviceOs = deviceOs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeviceOsVersion() {
    return deviceOsVersion;
  }
  public void setDeviceOsVersion(String deviceOsVersion) {
    this.deviceOsVersion = deviceOsVersion;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAppVersion() {
    return appVersion;
  }
  public void setAppVersion(String appVersion) {
    this.appVersion = appVersion;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getLastLoginUtcDateTime() {
    return lastLoginUtcDateTime;
  }
  public void setLastLoginUtcDateTime(Date lastLoginUtcDateTime) {
    this.lastLoginUtcDateTime = lastLoginUtcDateTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastLoginIpAddress() {
    return lastLoginIpAddress;
  }
  public void setLastLoginIpAddress(String lastLoginIpAddress) {
    this.lastLoginIpAddress = lastLoginIpAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceDto deviceDto = (DeviceDto) o;
    return (this.id == null ? deviceDto.id == null : this.id.equals(deviceDto.id)) &&
        (this.deviceOs == null ? deviceDto.deviceOs == null : this.deviceOs.equals(deviceDto.deviceOs)) &&
        (this.deviceOsVersion == null ? deviceDto.deviceOsVersion == null : this.deviceOsVersion.equals(deviceDto.deviceOsVersion)) &&
        (this.appVersion == null ? deviceDto.appVersion == null : this.appVersion.equals(deviceDto.appVersion)) &&
        (this.lastLoginUtcDateTime == null ? deviceDto.lastLoginUtcDateTime == null : this.lastLoginUtcDateTime.equals(deviceDto.lastLoginUtcDateTime)) &&
        (this.lastLoginIpAddress == null ? deviceDto.lastLoginIpAddress == null : this.lastLoginIpAddress.equals(deviceDto.lastLoginIpAddress));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.deviceOs == null ? 0: this.deviceOs.hashCode());
    result = 31 * result + (this.deviceOsVersion == null ? 0: this.deviceOsVersion.hashCode());
    result = 31 * result + (this.appVersion == null ? 0: this.appVersion.hashCode());
    result = 31 * result + (this.lastLoginUtcDateTime == null ? 0: this.lastLoginUtcDateTime.hashCode());
    result = 31 * result + (this.lastLoginIpAddress == null ? 0: this.lastLoginIpAddress.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceDto {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  deviceOs: ").append(deviceOs).append("\n");
    sb.append("  deviceOsVersion: ").append(deviceOsVersion).append("\n");
    sb.append("  appVersion: ").append(appVersion).append("\n");
    sb.append("  lastLoginUtcDateTime: ").append(lastLoginUtcDateTime).append("\n");
    sb.append("  lastLoginIpAddress: ").append(lastLoginIpAddress).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
