/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ExternalLoginDto {
  
  @SerializedName("loginProvider")
  private String loginProvider = null;
  @SerializedName("providerKey")
  private String providerKey = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLoginProvider() {
    return loginProvider;
  }
  public void setLoginProvider(String loginProvider) {
    this.loginProvider = loginProvider;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProviderKey() {
    return providerKey;
  }
  public void setProviderKey(String providerKey) {
    this.providerKey = providerKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalLoginDto externalLoginDto = (ExternalLoginDto) o;
    return (this.loginProvider == null ? externalLoginDto.loginProvider == null : this.loginProvider.equals(externalLoginDto.loginProvider)) &&
        (this.providerKey == null ? externalLoginDto.providerKey == null : this.providerKey.equals(externalLoginDto.providerKey));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.loginProvider == null ? 0: this.loginProvider.hashCode());
    result = 31 * result + (this.providerKey == null ? 0: this.providerKey.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalLoginDto {\n");
    
    sb.append("  loginProvider: ").append(loginProvider).append("\n");
    sb.append("  providerKey: ").append(providerKey).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
