/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ExternalLoginRequest {
  
  @SerializedName("loginProvider")
  private String loginProvider = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLoginProvider() {
    return loginProvider;
  }
  public void setLoginProvider(String loginProvider) {
    this.loginProvider = loginProvider;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalLoginRequest externalLoginRequest = (ExternalLoginRequest) o;
    return (this.loginProvider == null ? externalLoginRequest.loginProvider == null : this.loginProvider.equals(externalLoginRequest.loginProvider));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.loginProvider == null ? 0: this.loginProvider.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalLoginRequest {\n");
    
    sb.append("  loginProvider: ").append(loginProvider).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
