/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.kinny.login.models.ApiError;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ExternalLoginResponse {
  
  @SerializedName("href")
  private String href = null;
  @SerializedName("apiError")
  private ApiError apiError = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }
  public void setHref(String href) {
    this.href = href;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ApiError getApiError() {
    return apiError;
  }
  public void setApiError(ApiError apiError) {
    this.apiError = apiError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalLoginResponse externalLoginResponse = (ExternalLoginResponse) o;
    return (this.href == null ? externalLoginResponse.href == null : this.href.equals(externalLoginResponse.href)) &&
        (this.apiError == null ? externalLoginResponse.apiError == null : this.apiError.equals(externalLoginResponse.apiError));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.href == null ? 0: this.href.hashCode());
    result = 31 * result + (this.apiError == null ? 0: this.apiError.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalLoginResponse {\n");
    
    sb.append("  href: ").append(href).append("\n");
    sb.append("  apiError: ").append(apiError).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
