/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.kinny.login.models.ApiError;
import io.kinny.login.models.DeviceDto;
import io.kinny.login.models.ExternalLoginDto;
import io.kinny.login.models.UserDto;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProfileInformationResponse {
  
  @SerializedName("user")
  private UserDto user = null;
  @SerializedName("externalLogins")
  private List<ExternalLoginDto> externalLogins = null;
  @SerializedName("devices")
  private List<DeviceDto> devices = null;
  @SerializedName("apiError")
  private ApiError apiError = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public UserDto getUser() {
    return user;
  }
  public void setUser(UserDto user) {
    this.user = user;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ExternalLoginDto> getExternalLogins() {
    return externalLogins;
  }
  public void setExternalLogins(List<ExternalLoginDto> externalLogins) {
    this.externalLogins = externalLogins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<DeviceDto> getDevices() {
    return devices;
  }
  public void setDevices(List<DeviceDto> devices) {
    this.devices = devices;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ApiError getApiError() {
    return apiError;
  }
  public void setApiError(ApiError apiError) {
    this.apiError = apiError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileInformationResponse profileInformationResponse = (ProfileInformationResponse) o;
    return (this.user == null ? profileInformationResponse.user == null : this.user.equals(profileInformationResponse.user)) &&
        (this.externalLogins == null ? profileInformationResponse.externalLogins == null : this.externalLogins.equals(profileInformationResponse.externalLogins)) &&
        (this.devices == null ? profileInformationResponse.devices == null : this.devices.equals(profileInformationResponse.devices)) &&
        (this.apiError == null ? profileInformationResponse.apiError == null : this.apiError.equals(profileInformationResponse.apiError));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    result = 31 * result + (this.externalLogins == null ? 0: this.externalLogins.hashCode());
    result = 31 * result + (this.devices == null ? 0: this.devices.hashCode());
    result = 31 * result + (this.apiError == null ? 0: this.apiError.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileInformationResponse {\n");
    
    sb.append("  user: ").append(user).append("\n");
    sb.append("  externalLogins: ").append(externalLogins).append("\n");
    sb.append("  devices: ").append(devices).append("\n");
    sb.append("  apiError: ").append(apiError).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
