/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SendSmsRequest {
  
  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendSmsRequest sendSmsRequest = (SendSmsRequest) o;
    return (this.phoneNumber == null ? sendSmsRequest.phoneNumber == null : this.phoneNumber.equals(sendSmsRequest.phoneNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendSmsRequest {\n");
    
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
