/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserDto {
  
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("phoneNumber")
  private String phoneNumber = null;
  @SerializedName("phoneNumberConfirmed")
  private Boolean phoneNumberConfirmed = null;
  @SerializedName("emailConfirmed")
  private Boolean emailConfirmed = null;
  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPhoneNumberConfirmed() {
    return phoneNumberConfirmed;
  }
  public void setPhoneNumberConfirmed(Boolean phoneNumberConfirmed) {
    this.phoneNumberConfirmed = phoneNumberConfirmed;
  }


  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getEmailConfirmed() {
    return emailConfirmed;
  }
  public void setEmailConfirmed(Boolean emailConfirmed) {
    this.phoneNumberConfirmed = phoneNumberConfirmed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDto userDto = (UserDto) o;
    return (this.userId == null ? userDto.userId == null : this.userId.equals(userDto.userId)) &&
        (this.username == null ? userDto.username == null : this.username.equals(userDto.username)) &&
        (this.email == null ? userDto.email == null : this.email.equals(userDto.email)) &&
        (this.phoneNumber == null ? userDto.phoneNumber == null : this.phoneNumber.equals(userDto.phoneNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDto {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
