/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kinny.login.models;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserRegisterRequest {
  
  @SerializedName("username")
  private String username = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("confirmPassword")
  private String confirmPassword = null;
  @SerializedName("tos")
  private Boolean tos = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getConfirmPassword() {
    return confirmPassword;
  }
  public void setConfirmPassword(String confirmPassword) {
    this.confirmPassword = confirmPassword;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getTos() {
    return tos;
  }
  public void setTos(Boolean tos) {
    this.tos = tos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRegisterRequest userRegisterRequest = (UserRegisterRequest) o;
    return (this.username == null ? userRegisterRequest.username == null : this.username.equals(userRegisterRequest.username)) &&
        (this.email == null ? userRegisterRequest.email == null : this.email.equals(userRegisterRequest.email)) &&
        (this.password == null ? userRegisterRequest.password == null : this.password.equals(userRegisterRequest.password)) &&
        (this.confirmPassword == null ? userRegisterRequest.confirmPassword == null : this.confirmPassword.equals(userRegisterRequest.confirmPassword)) &&
        (this.tos == null ? userRegisterRequest.tos == null : this.tos.equals(userRegisterRequest.tos));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.confirmPassword == null ? 0: this.confirmPassword.hashCode());
    result = 31 * result + (this.tos == null ? 0: this.tos.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRegisterRequest {\n");
    
    sb.append("  username: ").append(username).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  confirmPassword: ").append(confirmPassword).append("\n");
    sb.append("  tos: ").append(tos).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
