/**
 * Login API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ApiError;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class ConfigResponse implements Serializable {
  
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("linkedExternalLogins")
  private List<String> linkedExternalLogins = null;
  @SerializedName("apiError")
  private ApiError apiError = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getLinkedExternalLogins() {
    return linkedExternalLogins;
  }
  public void setLinkedExternalLogins(List<String> linkedExternalLogins) {
    this.linkedExternalLogins = linkedExternalLogins;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ApiError getApiError() {
    return apiError;
  }
  public void setApiError(ApiError apiError) {
    this.apiError = apiError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigResponse configResponse = (ConfigResponse) o;
    return (this.userId == null ? configResponse.userId == null : this.userId.equals(configResponse.userId)) &&
        (this.linkedExternalLogins == null ? configResponse.linkedExternalLogins == null : this.linkedExternalLogins.equals(configResponse.linkedExternalLogins)) &&
        (this.apiError == null ? configResponse.apiError == null : this.apiError.equals(configResponse.apiError));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.linkedExternalLogins == null ? 0: this.linkedExternalLogins.hashCode());
    result = 31 * result + (this.apiError == null ? 0: this.apiError.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigResponse {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  linkedExternalLogins: ").append(linkedExternalLogins).append("\n");
    sb.append("  apiError: ").append(apiError).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
